#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoSupplier.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class MySupplierContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public MySupplierContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySupplierContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySupplierContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySupplierContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Supplier> Supplier
		{
			get
			{
				return this.GetTable<Supplier>();
			}
		}
		
		private void InsertSupplier(Supplier obj)
		{
			this.sp_SupplierInsert(obj.SupplierName, obj.Address1, obj.City, obj.State, obj.Country, obj.PhoneNumber, obj.Code);
		}
		
		private void UpdateSupplier(Supplier obj)
		{
			this.sp_SupplierUpdate(((System.Nullable<int>)(obj.ID)), obj.SupplierName, obj.Address1, obj.City, obj.State, obj.Country, obj.PhoneNumber, obj.Code);
		}
		
		private void DeleteSupplier(Supplier obj)
		{
			this.sp_SupplierInactive(((System.Nullable<int>)(obj.ID)));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SupplierInactive")]
		public int sp_SupplierInactive([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SupplierInsert")]
		public int sp_SupplierInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierName", DbType="NVarChar(30)")] string supplierName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(30)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="NVarChar(30)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="NVarChar(20)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="NVarChar(20)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(30)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="NVarChar(17)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supplierName, address1, city, state, country, phoneNumber, code);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SupplierSelectAll")]
		public ISingleResult<sp_SupplierSelectAllResult> sp_SupplierSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SupplierSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SupplierUpdate")]
		public int sp_SupplierUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierName", DbType="NVarChar(30)")] string supplierName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(30)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="NVarChar(30)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="NVarChar(20)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="NVarChar(20)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNumber", DbType="NVarChar(30)")] string phoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="NVarChar(17)")] string code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, supplierName, address1, city, state, country, phoneNumber, code);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Supplier")]
	public partial class Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Country;
		
		private int _HQID;
		
		private System.DateTime _LastUpdated;
		
		private string _State;
		
		private int _ID;
		
		private string _SupplierName;
		
		private string _ContactName;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _City;
		
		private string _Zip;
		
		private string _EmailAddress;
		
		private string _WebPageAddress;
		
		private string _Code;
		
		private System.Data.Linq.Binary _DBTimeStamp;
		
		private string _AccountNumber;
		
		private string _TaxNumber;
		
		private int _CurrencyID;
		
		private string _PhoneNumber;
		
		private string _FaxNumber;
		
		private string _CustomText1;
		
		private string _CustomText2;
		
		private string _CustomText3;
		
		private string _CustomText4;
		
		private string _CustomText5;
		
		private double _CustomNumber1;
		
		private double _CustomNumber2;
		
		private double _CustomNumber3;
		
		private double _CustomNumber4;
		
		private double _CustomNumber5;
		
		private System.Nullable<System.DateTime> _CustomDate1;
		
		private System.Nullable<System.DateTime> _CustomDate2;
		
		private System.Nullable<System.DateTime> _CustomDate3;
		
		private System.Nullable<System.DateTime> _CustomDate4;
		
		private System.Nullable<System.DateTime> _CustomDate5;
		
		private string _Notes;
		
		private string _Terms;
		
		private System.Guid _SyncGuid;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnHQIDChanging(int value);
    partial void OnHQIDChanged();
    partial void OnLastUpdatedChanging(System.DateTime value);
    partial void OnLastUpdatedChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSupplierNameChanging(string value);
    partial void OnSupplierNameChanged();
    partial void OnContactNameChanging(string value);
    partial void OnContactNameChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnWebPageAddressChanging(string value);
    partial void OnWebPageAddressChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDBTimeStampChanging(System.Data.Linq.Binary value);
    partial void OnDBTimeStampChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnTaxNumberChanging(string value);
    partial void OnTaxNumberChanged();
    partial void OnCurrencyIDChanging(int value);
    partial void OnCurrencyIDChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnFaxNumberChanging(string value);
    partial void OnFaxNumberChanged();
    partial void OnCustomText1Changing(string value);
    partial void OnCustomText1Changed();
    partial void OnCustomText2Changing(string value);
    partial void OnCustomText2Changed();
    partial void OnCustomText3Changing(string value);
    partial void OnCustomText3Changed();
    partial void OnCustomText4Changing(string value);
    partial void OnCustomText4Changed();
    partial void OnCustomText5Changing(string value);
    partial void OnCustomText5Changed();
    partial void OnCustomNumber1Changing(double value);
    partial void OnCustomNumber1Changed();
    partial void OnCustomNumber2Changing(double value);
    partial void OnCustomNumber2Changed();
    partial void OnCustomNumber3Changing(double value);
    partial void OnCustomNumber3Changed();
    partial void OnCustomNumber4Changing(double value);
    partial void OnCustomNumber4Changed();
    partial void OnCustomNumber5Changing(double value);
    partial void OnCustomNumber5Changed();
    partial void OnCustomDate1Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate1Changed();
    partial void OnCustomDate2Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate2Changed();
    partial void OnCustomDate3Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate3Changed();
    partial void OnCustomDate4Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate4Changed();
    partial void OnCustomDate5Changing(System.Nullable<System.DateTime> value);
    partial void OnCustomDate5Changed();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnTermsChanging(string value);
    partial void OnTermsChanged();
    partial void OnSyncGuidChanging(System.Guid value);
    partial void OnSyncGuidChanged();
    #endregion
		
		public Supplier()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HQID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int HQID
		{
			get
			{
				return this._HQID;
			}
			set
			{
				if ((this._HQID != value))
				{
					this.OnHQIDChanging(value);
					this.SendPropertyChanging();
					this._HQID = value;
					this.SendPropertyChanged("HQID");
					this.OnHQIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this.OnLastUpdatedChanging(value);
					this.SendPropertyChanging();
					this._LastUpdated = value;
					this.SendPropertyChanged("LastUpdated");
					this.OnLastUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this.OnSupplierNameChanging(value);
					this.SendPropertyChanging();
					this._SupplierName = value;
					this.SendPropertyChanged("SupplierName");
					this.OnSupplierNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this.OnContactNameChanging(value);
					this.SendPropertyChanging();
					this._ContactName = value;
					this.SendPropertyChanged("ContactName");
					this.OnContactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebPageAddress", DbType="NVarChar(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string WebPageAddress
		{
			get
			{
				return this._WebPageAddress;
			}
			set
			{
				if ((this._WebPageAddress != value))
				{
					this.OnWebPageAddressChanging(value);
					this.SendPropertyChanging();
					this._WebPageAddress = value;
					this.SendPropertyChanged("WebPageAddress");
					this.OnWebPageAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(17) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBTimeStamp", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DBTimeStamp
		{
			get
			{
				return this._DBTimeStamp;
			}
			set
			{
				if ((this._DBTimeStamp != value))
				{
					this.OnDBTimeStampChanging(value);
					this.SendPropertyChanging();
					this._DBTimeStamp = value;
					this.SendPropertyChanged("DBTimeStamp");
					this.OnDBTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxNumber", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TaxNumber
		{
			get
			{
				return this._TaxNumber;
			}
			set
			{
				if ((this._TaxNumber != value))
				{
					this.OnTaxNumberChanging(value);
					this.SendPropertyChanging();
					this._TaxNumber = value;
					this.SendPropertyChanged("TaxNumber");
					this.OnTaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CurrencyID
		{
			get
			{
				return this._CurrencyID;
			}
			set
			{
				if ((this._CurrencyID != value))
				{
					this.OnCurrencyIDChanging(value);
					this.SendPropertyChanging();
					this._CurrencyID = value;
					this.SendPropertyChanged("CurrencyID");
					this.OnCurrencyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FaxNumber
		{
			get
			{
				return this._FaxNumber;
			}
			set
			{
				if ((this._FaxNumber != value))
				{
					this.OnFaxNumberChanging(value);
					this.SendPropertyChanging();
					this._FaxNumber = value;
					this.SendPropertyChanged("FaxNumber");
					this.OnFaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText1", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CustomText1
		{
			get
			{
				return this._CustomText1;
			}
			set
			{
				if ((this._CustomText1 != value))
				{
					this.OnCustomText1Changing(value);
					this.SendPropertyChanging();
					this._CustomText1 = value;
					this.SendPropertyChanged("CustomText1");
					this.OnCustomText1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText2", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CustomText2
		{
			get
			{
				return this._CustomText2;
			}
			set
			{
				if ((this._CustomText2 != value))
				{
					this.OnCustomText2Changing(value);
					this.SendPropertyChanging();
					this._CustomText2 = value;
					this.SendPropertyChanged("CustomText2");
					this.OnCustomText2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText3", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CustomText3
		{
			get
			{
				return this._CustomText3;
			}
			set
			{
				if ((this._CustomText3 != value))
				{
					this.OnCustomText3Changing(value);
					this.SendPropertyChanging();
					this._CustomText3 = value;
					this.SendPropertyChanged("CustomText3");
					this.OnCustomText3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText4", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CustomText4
		{
			get
			{
				return this._CustomText4;
			}
			set
			{
				if ((this._CustomText4 != value))
				{
					this.OnCustomText4Changing(value);
					this.SendPropertyChanging();
					this._CustomText4 = value;
					this.SendPropertyChanged("CustomText4");
					this.OnCustomText4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomText5", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CustomText5
		{
			get
			{
				return this._CustomText5;
			}
			set
			{
				if ((this._CustomText5 != value))
				{
					this.OnCustomText5Changing(value);
					this.SendPropertyChanging();
					this._CustomText5 = value;
					this.SendPropertyChanged("CustomText5");
					this.OnCustomText5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber1", DbType="Float NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public double CustomNumber1
		{
			get
			{
				return this._CustomNumber1;
			}
			set
			{
				if ((this._CustomNumber1 != value))
				{
					this.OnCustomNumber1Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber1 = value;
					this.SendPropertyChanged("CustomNumber1");
					this.OnCustomNumber1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber2", DbType="Float NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public double CustomNumber2
		{
			get
			{
				return this._CustomNumber2;
			}
			set
			{
				if ((this._CustomNumber2 != value))
				{
					this.OnCustomNumber2Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber2 = value;
					this.SendPropertyChanged("CustomNumber2");
					this.OnCustomNumber2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber3", DbType="Float NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public double CustomNumber3
		{
			get
			{
				return this._CustomNumber3;
			}
			set
			{
				if ((this._CustomNumber3 != value))
				{
					this.OnCustomNumber3Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber3 = value;
					this.SendPropertyChanged("CustomNumber3");
					this.OnCustomNumber3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber4", DbType="Float NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public double CustomNumber4
		{
			get
			{
				return this._CustomNumber4;
			}
			set
			{
				if ((this._CustomNumber4 != value))
				{
					this.OnCustomNumber4Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber4 = value;
					this.SendPropertyChanged("CustomNumber4");
					this.OnCustomNumber4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber5", DbType="Float NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public double CustomNumber5
		{
			get
			{
				return this._CustomNumber5;
			}
			set
			{
				if ((this._CustomNumber5 != value))
				{
					this.OnCustomNumber5Changing(value);
					this.SendPropertyChanging();
					this._CustomNumber5 = value;
					this.SendPropertyChanged("CustomNumber5");
					this.OnCustomNumber5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate1", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CustomDate1
		{
			get
			{
				return this._CustomDate1;
			}
			set
			{
				if ((this._CustomDate1 != value))
				{
					this.OnCustomDate1Changing(value);
					this.SendPropertyChanging();
					this._CustomDate1 = value;
					this.SendPropertyChanged("CustomDate1");
					this.OnCustomDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate2", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CustomDate2
		{
			get
			{
				return this._CustomDate2;
			}
			set
			{
				if ((this._CustomDate2 != value))
				{
					this.OnCustomDate2Changing(value);
					this.SendPropertyChanging();
					this._CustomDate2 = value;
					this.SendPropertyChanged("CustomDate2");
					this.OnCustomDate2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate3", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CustomDate3
		{
			get
			{
				return this._CustomDate3;
			}
			set
			{
				if ((this._CustomDate3 != value))
				{
					this.OnCustomDate3Changing(value);
					this.SendPropertyChanging();
					this._CustomDate3 = value;
					this.SendPropertyChanged("CustomDate3");
					this.OnCustomDate3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate4", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CustomDate4
		{
			get
			{
				return this._CustomDate4;
			}
			set
			{
				if ((this._CustomDate4 != value))
				{
					this.OnCustomDate4Changing(value);
					this.SendPropertyChanging();
					this._CustomDate4 = value;
					this.SendPropertyChanged("CustomDate4");
					this.OnCustomDate4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDate5", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CustomDate5
		{
			get
			{
				return this._CustomDate5;
			}
			set
			{
				if ((this._CustomDate5 != value))
				{
					this.OnCustomDate5Changing(value);
					this.SendPropertyChanging();
					this._CustomDate5 = value;
					this.SendPropertyChanged("CustomDate5");
					this.OnCustomDate5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terms", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Terms
		{
			get
			{
				return this._Terms;
			}
			set
			{
				if ((this._Terms != value))
				{
					this.OnTermsChanging(value);
					this.SendPropertyChanging();
					this._Terms = value;
					this.SendPropertyChanged("Terms");
					this.OnTermsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyncGuid", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid SyncGuid
		{
			get
			{
				return this._SyncGuid;
			}
			set
			{
				if ((this._SyncGuid != value))
				{
					this.OnSyncGuidChanging(value);
					this.SendPropertyChanging();
					this._SyncGuid = value;
					this.SendPropertyChanged("SyncGuid");
					this.OnSyncGuidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_SupplierSelectAllResult
	{
		
		private int _ID;
		
		private string _SupplierName;
		
		private string _Address1;
		
		private string _City;
		
		private string _State;
		
		private string _Country;
		
		private string _PhoneNumber;
		
		private string _Code;
		
		private double _CustomNumber1;
		
		public sp_SupplierSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string SupplierName
		{
			get
			{
				return this._SupplierName;
			}
			set
			{
				if ((this._SupplierName != value))
				{
					this._SupplierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(17) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomNumber1", DbType="Float NOT NULL")]
		public double CustomNumber1
		{
			get
			{
				return this._CustomNumber1;
			}
			set
			{
				if ((this._CustomNumber1 != value))
				{
					this._CustomNumber1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
